### ISSUE TITLE
Замечания к вёрстке "Инциденты и заявки"

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#101]
см скрин:
![001](https://cloud.githubusercontent.com/assets/6616341/16734157/2d64fbce-478d-11e6-8089-1466895aa4a2.png)

**Comment by ikudin** [comment]
1. Кнопку xls сделал чуть меньше, теперь идет вровень. Сделал хинт при наводке.
2. Кнопку создать заявку сделал больше, текст в ней выровнял по вертикали по середине
3. Текстовое поле для комментария сделал изменяющимся только по вертикали.
4. Выравнивание сделал
5. Заголовок "комментарии" сдвинул чуть ниже вровень с от до

**Comment by oknoproblem** [comment]
А на вкладке Сообщения забыл сделать кнопку XLS маленькой.

Одинаковые вещи, должны одинаково выглядеть.

**Comment by indvoa** [comment]
Проверено в обновлении от 04.02.2017
