### ISSUE TITLE
кнопка "перейти к сообщению" неактивна для Не документов. Должна быть активна!

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#132]
Кнопка должна быть активна для сообщений типов квитанция/ТК/Уведомление так же как и для документов и переводить на фильтрованный список с отображением сообщения по которому сгенерирован инцидент.

На данный момент, как минимум для квитанций переход осуществляется не на сообщение, что некорректно.

**Comment by ikudin** [comment]
у меня активна. скинь бэкап базы, где такое есть

**Comment by indvoa** [comment]
Проверено в обновлении от 04.02.2017
