### ISSUE TITLE
Дата создания заявки по гринвичу

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#142]
Дата создания заявки должна быть по локальному времени, сейчас по гринвичу
![001](https://cloud.githubusercontent.com/assets/6616341/19035861/e64e279a-8974-11e6-9eae-c8e5c1b7482e.png)

**Comment by ikudin** [comment]
берется время сервера, вроде как

**Comment by oknoproblem** [comment]
нет, время сервера другое.

**Comment by indvoa** [comment]
Перенесено в Jira
