### ISSUE TITLE
Пользователю с правами Оператор ГУ не должна быть доступна кнопка "Изменить срок выполнения" у заявок/инцидентов

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#143]
Пользователю с правами Оператор ГУ не должна быть доступна кнопка "Изменить срок выполнения" у заявок/инцидентов.

Сейчас доступна, нажать можно но реально запись о сроке не добавляется, у Операторов вообще надо убрать данную кнопку.

**Comment by ikudin** [comment]
сделал,сейчасс скину

**Comment by indvoa** [comment]
Проверено в обновлении от 04.02.2017
