### ISSUE TITLE
Сводка: некорректный состав атрибутов записей в блоках "Новых (незакрытых) заявок", " Новых (не устранённых) инцидентов"

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#26]
Согласно прототипу у каждой заявки должен быть следующий состав атрибутов:
- дата
- номер заявки
- Первые 40 символов темы заявки
- № документа (если указан, если нет пустое значение)
- Отправитель заявки (Краткое имя из справочника ведомств), либо отправитель документа в случае если заявка создана по документу.
- Дата регистрации заявки
- Получатель документа в случае если заявка создана по документу (либо пустое значение)

В данный момент в данной карточке есть только:
- дата
- номер заявки
- тема ПОЛНОСТЬЮ (должна быть не более 40 символов)
- тип заявки.

**Comment by ikudin** [comment]
Там еще есть податель - ведомство, от имени которого пользователь создает заявку (одно из тех, с которыми связан пользователь).
На данный момент все есть.

**Comment by ikudin** [comment]
сделано

**Comment by oknoproblem** [comment]
Первые 40 символов темы заявки

в данный момент полностью:
![Uploading 001.png…]()

**Comment by ikudin** [comment]
все

**Comment by oknoproblem** [comment]
ну, получилось слишком коротко теперь... согласно прототипу надо 40 символов... сейчас 23. 
Я не придираюсь, я тестирую согласно требованиям.

**Comment by oknoproblem** [comment]
Актуальна

**Comment by ikudin** [comment]
увеличил пространство для темы до 300px. Дело в том, что в это пространство не всегда влезет 40 символов)

**Comment by oknoproblem** [comment]
Тут проблема, тут несоответствие Прототипу всё равно, так как кол-во символов в прототипе регламентировано - 40.

В указанное пространство практически никогда не влезет 40 символов, даже 30 символов там будет очень редко.

Если не собираешься править, оставь задачу открытой и поставь лэйбл wontfix

**Comment by ikudin** [comment]
что мы тут в результате делаем? я могу прикрутить скрипт измерения ширины текста и для каждого элемента выставлять ширину, равную 40 символам. но смысл???

**Comment by indvoa** [comment]
Перенесено в Jira: PORT-46
