### ISSUE TITLE
При развёртывании фильтра поиска на страницах Сообщений и заявки и инциденты весь интерфейс "прыгает" влево.

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#89]
При развёртывании фильтра поиска на страницах Сообщений и заявки и инциденты весь интерфейс "прыгает" влево.

Пикселей так на 10.

**Comment by oknoproblem** [comment]
из за правого скролбара

**Comment by ikudin** [comment]
это естественное поведение браузера. прыгает не интерфейс, а окно браузера

**Comment by oknoproblem** [comment]
Я участвовал во многих проектах разработки вёб ГУИ фронтенда, ни в одном из них не было проблемы с "прыганием" всего ГУЯ при появлении скрола.

Считаю это серьёзным фронтенд дефектом.

**Comment by indvoa** [comment]
Проверено в обновлении от 04.02.2017. Не наблюдается на странице "Инциденты и заявки", наблюдается на странице "Сообщения", на что занесена ошибка PORT-44 в Jira.
