### ISSUE TITLE
Сортировка комментариев по времени у заявок/инцидентов не работает

### ISSUE THREAD

**Issue by oknoproblem** [indvoa/medo_agent#97]
Шаги:
- открыть карточку заявки/инцидента с комментариями
- выбрать фильтр периода таким образом чтобы в период не попадал ни один комментарий

Ожидается:
- отобразится пустой список комментариев

Получено:
- список не изменился

![001](https://cloud.githubusercontent.com/assets/6616341/16724983/eecd0d2c-475d-11e6-8f02-f7dad7e3ad26.png)

**Comment by oknoproblem** [comment]
1) Время фильтрации на 3 часа вперёд
2) Если задать период, сортировка не работает:
![001](https://cloud.githubusercontent.com/assets/6616341/17295176/9037defc-5803-11e6-944f-2bd9a7e556ee.png)

**Comment by ikudin** [comment]
сортировка всегда работает. а вот с временем фильтрации пока ничего придумать не могу.

**Comment by ikudin** [comment]
тут проверь, пожалуйста сортировку. если работает, то закрываем и смоздаем отдельный баг нужен на сдвиг времени по всему приложению

**Comment by indvoa** [comment]
Проверено в обновлении от 04.02.2017. Сортировка комментариев по дате работает, фильтрация - нет: заведен баг PORT-43 в Jira.
